from PyQt5 import QtCore, QtGui, QtWidgets
import logging as log
from ..Vars.Global import *
from PyQt5.QtGui import QIcon
from ..GameUser.UserFile import UserFile
from ..GameUser.BlizzardUser import BlizzardUser

class BlizzardUI(QObject):

    log.basicConfig(filename = LOG_FILE_NAME, level = log.DEBUG, format = LOG_FORMAT)

    game_checkboxes = []
    games_checked = []

    def __init__(self):
        super().__init__()
        log.info("BlizzardUI init called")
        blizzard_dialog = QtWidgets.QDialog()
        blizzard_dialog.setWindowFlags(blizzard_dialog.windowFlags() & ~QtCore.Qt.WindowContextHelpButtonHint)
        blizzard_dialog.setWindowIcon(QIcon(WIN_ICON))
        self.setupUi(blizzard_dialog)
        
        self.game_checkboxes.append(self.sc2_checkbox)
        self.game_checkboxes.append(self.broodwar_checkbox)
        self.game_checkboxes.append(self.d3_checkbox)
        self.game_checkboxes.append(self.wow_checkbox)
        self.game_checkboxes.append(self.hearthstone_checkbox)
        self.game_checkboxes.append(self.overwatch_checkbox)

        self.region = None
        self.real_id = None

        blizzard_dialog.show()
        blizzard_dialog.exec_()

    def setupUi(self, blizzard_dialog):
        blizzard_dialog.setObjectName("blizzard_dialog")
        blizzard_dialog.resize(600, 400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(blizzard_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.real_id_horz_layout = QtWidgets.QHBoxLayout()
        self.real_id_horz_layout.setObjectName("real_id_horz_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.real_id_horz_layout.addItem(spacerItem)
        self.real_id_label = QtWidgets.QLabel(blizzard_dialog)
        self.real_id_label.setMinimumSize(QtCore.QSize(50, 25))
        self.real_id_label.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.real_id_label.setFont(font)
        self.real_id_label.setObjectName("real_id_label")
        self.real_id_horz_layout.addWidget(self.real_id_label)
        self.real_id_entry = QtWidgets.QLineEdit(blizzard_dialog)
        self.real_id_entry.setMinimumSize(QtCore.QSize(150, 25))
        self.real_id_entry.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.real_id_entry.setFont(font)
        self.real_id_entry.setObjectName("real_id_entry")
        self.real_id_horz_layout.addWidget(self.real_id_entry)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.real_id_horz_layout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.real_id_horz_layout)
        self.region_horz_layout = QtWidgets.QHBoxLayout()
        self.region_horz_layout.setObjectName("region_horz_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.region_horz_layout.addItem(spacerItem2)
        self.region_combobox = QtWidgets.QComboBox(blizzard_dialog)
        self.region_combobox.setMinimumSize(QtCore.QSize(100, 30))
        self.region_combobox.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.region_combobox.setFont(font)
        self.region_combobox.setObjectName("region_combobox")
        self.region_combobox.addItem("")
        self.region_combobox.addItem("")
        self.region_combobox.addItem("")
        self.region_combobox.addItem("")
        self.region_combobox.addItem("")
        self.region_horz_layout.addWidget(self.region_combobox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.region_horz_layout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.region_horz_layout)
        self.select_horz_layout = QtWidgets.QHBoxLayout()
        self.select_horz_layout.setObjectName("select_horz_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.select_horz_layout.addItem(spacerItem4)
        self.select_blizz_games_label = QtWidgets.QLabel(blizzard_dialog)
        self.select_blizz_games_label.setMinimumSize(QtCore.QSize(180, 35))
        self.select_blizz_games_label.setMaximumSize(QtCore.QSize(180, 35))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(LARGE_FONT_POINT)
        self.select_blizz_games_label.setFont(font)
        self.select_blizz_games_label.setAlignment(QtCore.Qt.AlignCenter)
        self.select_blizz_games_label.setWordWrap(True)
        self.select_blizz_games_label.setObjectName("select_blizz_games_label")
        self.select_horz_layout.addWidget(self.select_blizz_games_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.select_horz_layout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.select_horz_layout)
        self.sc2_horz_layout = QtWidgets.QHBoxLayout()
        self.sc2_horz_layout.setObjectName("sc2_horz_layout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sc2_horz_layout.addItem(spacerItem6)
        self.sc2_checkbox = QtWidgets.QCheckBox(blizzard_dialog)
        self.sc2_checkbox.setMinimumSize(QtCore.QSize(170, 20))
        self.sc2_checkbox.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.sc2_checkbox.setFont(font)
        self.sc2_checkbox.setObjectName("sc2_checkbox")
        self.sc2_horz_layout.addWidget(self.sc2_checkbox)
        self.hearthstone_checkbox = QtWidgets.QCheckBox(blizzard_dialog)
        self.hearthstone_checkbox.setMinimumSize(QtCore.QSize(170, 20))
        self.hearthstone_checkbox.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.hearthstone_checkbox.setFont(font)
        self.hearthstone_checkbox.setObjectName("hearthstone_checkbox")
        self.sc2_horz_layout.addWidget(self.hearthstone_checkbox)
        self.d3_checkbox = QtWidgets.QCheckBox(blizzard_dialog)
        self.d3_checkbox.setMinimumSize(QtCore.QSize(170, 20))
        self.d3_checkbox.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.d3_checkbox.setFont(font)
        self.d3_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.d3_checkbox.setObjectName("d3_checkbox")
        self.sc2_horz_layout.addWidget(self.d3_checkbox)
        self.verticalLayout_2.addLayout(self.sc2_horz_layout)
        self.broodwar_horz_layout = QtWidgets.QHBoxLayout()
        self.broodwar_horz_layout.setObjectName("broodwar_horz_layout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.broodwar_horz_layout.addItem(spacerItem7)
        self.broodwar_checkbox = QtWidgets.QCheckBox(blizzard_dialog)
        self.broodwar_checkbox.setMinimumSize(QtCore.QSize(170, 20))
        self.broodwar_checkbox.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.broodwar_checkbox.setFont(font)
        self.broodwar_checkbox.setObjectName("broodwar_checkbox")
        self.broodwar_horz_layout.addWidget(self.broodwar_checkbox)
        self.wow_checkbox = QtWidgets.QCheckBox(blizzard_dialog)
        self.wow_checkbox.setMinimumSize(QtCore.QSize(170, 20))
        self.wow_checkbox.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.wow_checkbox.setFont(font)
        self.wow_checkbox.setObjectName("wow_checkbox")
        self.broodwar_horz_layout.addWidget(self.wow_checkbox)
        self.overwatch_checkbox = QtWidgets.QCheckBox(blizzard_dialog)
        self.overwatch_checkbox.setMinimumSize(QtCore.QSize(170, 20))
        self.overwatch_checkbox.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.overwatch_checkbox.setFont(font)
        self.overwatch_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwatch_checkbox.setObjectName("overwatch_checkbox")
        self.broodwar_horz_layout.addWidget(self.overwatch_checkbox)
        self.verticalLayout_2.addLayout(self.broodwar_horz_layout)
        self.submit_horz_layout = QtWidgets.QHBoxLayout()
        self.submit_horz_layout.setObjectName("submit_horz_layout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submit_horz_layout.addItem(spacerItem8)
        self.submit_button = QtWidgets.QPushButton(blizzard_dialog)
        self.submit_button.setMinimumSize(QtCore.QSize(100, 30))
        self.submit_button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.submit_horz_layout.addWidget(self.submit_button)
        self.cancel_button = QtWidgets.QPushButton(blizzard_dialog)
        self.cancel_button.setMinimumSize(QtCore.QSize(100, 30))
        self.cancel_button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily(FONT_NAME)
        font.setPointSize(NORM_FONT_POINT)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.submit_horz_layout.addWidget(self.cancel_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submit_horz_layout.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.submit_horz_layout)

        self.retranslateUi(blizzard_dialog)
        QtCore.QMetaObject.connectSlotsByName(blizzard_dialog)

    def retranslateUi(self, blizzard_dialog):
        _translate = QtCore.QCoreApplication.translate
        blizzard_dialog.setWindowTitle(_translate("blizzard_dialog", "Blizzard Games"))
        self.real_id_label.setText(_translate("blizzard_dialog", "Real ID"))
        self.region_combobox.setToolTip(_translate("blizzard_dialog", "Choose region"))
        self.region_combobox.setItemText(0, _translate("blizzard_dialog", "Region"))
        self.region_combobox.setItemText(1, _translate("blizzard_dialog", "Americas"))
        self.region_combobox.setItemText(2, _translate("blizzard_dialog", "Europe"))
        self.region_combobox.setItemText(3, _translate("blizzard_dialog", "Asia"))
        self.region_combobox.setItemText(4, _translate("blizzard_dialog", "China"))
        self.select_blizz_games_label.setText(_translate("blizzard_dialog", "Select your games"))
        self.sc2_checkbox.setText(_translate("blizzard_dialog", "StarCraft II"))
        self.hearthstone_checkbox.setText(_translate("blizzard_dialog", "Hearthstone"))
        self.d3_checkbox.setText(_translate("blizzard_dialog", "Diablo 3"))
        self.broodwar_checkbox.setText(_translate("blizzard_dialog", "StarCraft: Brood War"))
        self.wow_checkbox.setText(_translate("blizzard_dialog", "World of Warcraft"))
        self.overwatch_checkbox.setText(_translate("blizzard_dialog", "Overwatch"))
        self.submit_button.setText(_translate("blizzard_dialog", "Submit"))
        self.cancel_button.setText(_translate("blizzard_dialog", "Cancel"))

    def _submit_clicked(self):
        self.region = self.region_combobox.currentText()
        self.real_id = self.real_id_entry.text().strip()

        for checkbox in self.game_checkboxes:
            if checkbox.isChecked():
                self.games_checked.append(checkbox.text())

        if self._conditions_met():
            blizz_user = BlizzardUser(self.real_id, self.region, self.games_checked)
            user_file = UserFile(blizz_user)
            user_file.create_user_file()

    #just putting all the conditions in their own method for one easy call rather than cascading if statements
    def _conditions_met(self):
        if not self.region == "Region" and len(self.games_checked) > 0 and not self.real_id == "":
            return True
        return False